dist: bionic
language: python
python:
  - "3.7"
addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11
      - postgresql-contrib-11
before_install:
  - ls -a /var/run/postgres
  - sudo -u postgres psql -U postgres -p 5433 -d postgres -c "alter user postgres with password 'hj38f3Ntr';"
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - export POSTGRES_USER="postgres" && export POSTGRES_PASSWORD="hj38f3Ntr" && export POSTGRES_PORT=5433
  - python3 -m coverage run ./manage.py test
  - codecov
  - rm -rf chord_metadata_service
  - python3 -m coverage run ./manage.py test chord_metadata_service
