# Generated by Django 5.0.1 on 2024-01-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='date_resolution',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='test_date',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_birth',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='date_of_death',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date_of_followup',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='date_of_relapse',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='date_of_diagnosis',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimen_collection_date',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_end_date',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='treatment_start_date',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
