# Generated by Django 5.0.1 on 2024-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0002_donor_date_resolution_alter_biomarker_test_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='date_alive_after_lost_to_followup',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
