# Generated by Django 6.0.6 on 2026-06-29 23:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0002_alter_donor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='collaborators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='context',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='funding_sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='lead_organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pancan_cohort',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='pancan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='participant_criteria',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='principal_investigators',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='publication_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
