# Generated by Django 6.0.6 on 2026-06-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0003_program_collaborators_program_context_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='date_alive_after_lost_to_followup',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='lost_to_followup_after_clinical_event_identifier',
        ),
        migrations.AddField(
            model_name='donor',
            name='date_of_death_is_estimated',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='lost_to_follow_up',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
