# Generated by Django 5.0.1 on 2024-01-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0003_alter_donor_date_alive_after_lost_to_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biomarker',
            name='ca125',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='cea',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='psa_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemotherapy',
            name='actual_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemotherapy',
            name='prescribed_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comorbidity',
            name='age_at_comorbidity_diagnosis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hormonetherapy',
            name='actual_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hormonetherapy',
            name='prescribed_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='actual_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='immunotherapy',
            name='prescribed_cumulative_drug_dose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='primarydiagnosis',
            name='number_lymph_nodes_positive',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='radiation_therapy_dosage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='radiation',
            name='radiation_therapy_fractions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='greatest_dimension_tumour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='tumour_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='tumour_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='days_per_cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='number_of_cycles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
