# Generated by Django 6.0.6 on 2026-07-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0004_remove_donor_date_alive_after_lost_to_followup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleregistration',
            name='specimen_tissue_source',
        ),
        migrations.RemoveField(
            model_name='sampleregistration',
            name='specimen_type',
        ),
        migrations.RemoveField(
            model_name='sampleregistration',
            name='tumour_normal_designation',
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimen_tissue_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimen_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='tumour_normal_designation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
