# Generated by Django 6.0.6 on 2026-07-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0004_remove_donor_date_alive_after_lost_to_followup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='ca19_9',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biomarker',
            name='ca19_9_not_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='ca125',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='cea',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='biomarker',
            name='psa_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
