# Generated by Django 6.0.3 on 2026-07-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0005_biomarker_ca19_9_biomarker_ca19_9_not_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='margin_types_involved',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='margin_types_not_assessed',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='margin_types_not_involved',
        ),
        migrations.AddField(
            model_name='surgery',
            name='margins_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
