# Generated by Django 6.0.6 on 2026-07-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0005_remove_sampleregistration_specimen_tissue_source_and_more'),
        ('mohpackets', '0006_remove_surgery_margin_types_involved_and_more'),
    ]

    operations = [
    ]
