# Generated by Django 6.0.6 on 2026-07-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0006_merge_20260717_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_setting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
