# Generated by Django 6.0.6 on 2026-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0007_merge_20260720_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='treatment_setting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
