# Generated by Django 6.0.3 on 2026-07-21 05:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohpackets', '0008_treatment_treatment_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiopharmaceuticalTherapy',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('submitter_donor_id', models.CharField(max_length=64)),
                ('submitter_treatment_id', models.CharField(max_length=64)),
                ('rxnorm_code', models.CharField(blank=True, max_length=64, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('radionuclide', models.CharField(blank=True, max_length=255, null=True)),
                ('radionuclide_other', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.JSONField(blank=True, null=True)),
                ('end_date', models.JSONField(blank=True, null=True)),
                ('cumulative_drug_dose', models.FloatField(blank=True, null=True)),
                ('cumulative_drug_dose_not_available', models.BooleanField(default=False)),
                ('drug_dose_units', models.CharField(blank=True, max_length=64, null=True)),
                ('mass_value', models.FloatField(blank=True, null=True)),
                ('mass_value_not_available', models.BooleanField(default=False)),
                ('mass_unit_ucum', models.CharField(blank=True, max_length=64, null=True)),
                ('number_of_cycles', models.IntegerField(blank=True, null=True)),
                ('number_of_cycles_not_available', models.BooleanField(default=False)),
                ('donor_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mohpackets.donor')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mohpackets.program')),
                ('treatment_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mohpackets.treatment')),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
    ]
