from datetime import datetime

def main():

    with open("classes.mmd", "r") as classes_file:
        class_diagram = classes_file.read()

        er_diagram = class_diagram.replace("class ", "")
        er_diagram = er_diagram.replace("classDiagram", "erDiagram")
        er_diagram = er_diagram.replace("  Meta {\n    ordering : list\n  }\n", "")
        er_diagram = er_diagram.replace("  AutoDateTimeField {\n    pre_save(model_instance, add)\n  }\n", "")
        er_diagram = er_diagram.replace(": ", "")
        er_diagram = er_diagram.replace("AutoDateTimeField --* Program updated", "")
        er_diagram = er_diagram.replace("updated", "updated AutoDateTimeField")

    with open("er_diagram.md", "w+") as er_file:
        er_file.write("This file is automatically generated using the `pyreverse` command from the `pylint` library, the `models.py` script and the `make_er_diagrams.py` script. Do not edit it directly,\n\n")
        er_file.write(f"This file was last generated on {datetime.today().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        er_file.write("To regenerate this file, run the following from the commandline in the current directory: \n```\npip install pylint\npyreverse -o mmd ./models.py\npython make_er_diagrams.py\n```\n\n")
        er_file.write("You can view the below diagram in a nicer viewer by hitting the 'copy' button and pasting it into the live editor on [mermaid.live](https://mermaid.live)\n\n")
        er_file.write("```mermaid\n")
        er_file.write(er_diagram)
        # linking entities
        er_file.write('Program ||--|{ Donor : ""\n')
        er_file.write('Program ||--|{ PrimaryDiagnosis : ""\n')
        er_file.write('Program ||--o{ Comorbidity : ""\n')
        er_file.write('Program ||--o{ Biomarker : ""\n')
        er_file.write('Program ||--o{ Exposure : ""\n')
        er_file.write('Program ||--o{ FollowUp : ""\n')
        er_file.write('Program ||--|{ Specimen : ""\n')
        er_file.write('Program ||--|{ Treatment : ""\n')
        er_file.write('Program ||--|{ SampleRegistration : ""\n')
        er_file.write('Program ||--|{ Chemotherapy : ""\n')
        er_file.write('Program ||--|{ HormoneTherapy : ""\n')
        er_file.write('Program ||--|{ Immunotherapy : ""\n')
        er_file.write('Program ||--|{ Radiation : ""\n')
        er_file.write('Program ||--|{ Surgery : ""\n')
        er_file.write('Donor ||--|{ PrimaryDiagnosis : ""\n')
        er_file.write('Donor ||--o{ Comorbidity : ""\n')
        er_file.write('Donor ||--o{ Biomarker : "" \n')
        er_file.write('Donor ||--o{ Exposure : "" \n')
        er_file.write('Donor ||--o{ FollowUp : "" \n')
        er_file.write('Donor ||--|{ Specimen : "" \n')
        er_file.write('Donor ||--|{ Treatment : "" \n')
        er_file.write('Donor ||--|{ SampleRegistration : "" \n')
        er_file.write('Donor ||--|{ Chemotherapy : "" \n')
        er_file.write('Donor ||--|{ HormoneTherapy : "" \n')
        er_file.write('Donor ||--|{ Immunotherapy : "" \n')
        er_file.write('Donor ||--|{ Radiation : "" \n')
        er_file.write('Donor ||--|{ Surgery : "" \n')
        er_file.write('PrimaryDiagnosis ||--|{ Specimen : "" \n')
        er_file.write('PrimaryDiagnosis ||--|{ Treatment : "" \n')
        er_file.write('PrimaryDiagnosis ||--o{ FollowUp : "" \n')
        er_file.write('Specimen ||--|{ SampleRegistration : "" \n')
        er_file.write('Treatment ||--|{ Chemotherapy : "" \n')
        er_file.write('Treatment ||--|{ HormoneTherapy : "" \n')
        er_file.write('Treatment ||--|{ Immunotherapy : "" \n')
        er_file.write('Treatment ||--|{ Radiation : "" \n')
        er_file.write('Treatment ||--|{ Surgery : "" \n')
        er_file.write('Treatment ||--|{ FollowUp : "" \n')
        er_file.write('\n```\n')

if __name__ == '__main__':
    main()


