openapi: 3.0.3
info:
  title: MoH Query Service API
  version: 2.3.0
  description: This is the RESTful API for the MoH Query Service
paths:
  /v2/discovery/query/:
    get:
      operationId: authorized_donors_list
      description: Dicovery query for the list of applicable donors' ids/program_ids/submitter_specimen_IDs.
      parameters:
      - in: query
        name: treatment_type
        schema:
          type: array
          items:
            type: string
      - in: query
        name: primary_site
        schema:
          type: array
          items:
            type: string
      - in: query
        name: chemotherapy_drug_name
        schema:
          type: array
          items:
            type: string
      - in: query
        name: immunotherapy_drug_name
        schema:
          type: array
          items:
            type: string  
      - in: query
        name: hormone_therapy_drug_name
        schema:
          type: array
          items:
            type: string
      - in: query
        name: exclude_cohorts
        description: Cohorts to be exclude results frmo
        schema:
          type: array
          items:
            type: string
      tags:
      - authorized
      security:
      - localAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DonorWithSamplesList'
          description: ''
components:
  schemas:
    DonorWithSamples:
      type: object
      properties:
        submitter_donor_id:
          type: string
          maxLength: 64
          pattern: ^[A-Za-z0-9\-\._]{1,64}
        program_id:
          type: string
        age_at_diagnosis:
          type: string
          description: One of 0-19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80+, or null
        submitter_sample_ids:
          type: array
          items:
            type: string
        treatment_type:
          type: array
          items:
            type: string
        primary_sites:
          type: array
          items:
            type: string
      required:
      - program_id
      - submitter_donor_id
    DonorWithSamplesList:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/DonorWithSamples'