components:
  schemas: {}
info:
  description: This is the RESTful API for the MoH Service.
  title: MoH Service API
  version: 4.6.0
openapi: 3.1.0
paths:
  /v2/service-info:
    get:
      operationId: chord_metadata_service_mohpackets_apis_core_service_info
      parameters: []
      responses:
        '200':
          description: OK
      summary: Service Info
servers: []

