name: PR Merge Workflow

on:
  push:
    branches:
      - master
      - develop
      - sonchau/uuid_with_fk

jobs:
  second_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install widdershins
        run: npm install -g widdershins

      - name: Install PyYAML
        run: pip install PyYAML
      
      - name: Convert schema to OpenAPI documentation
        run: |
          npx widdershins ./chord_metadata_service/mohpackets/docs/schema.json -o ./chord_metadata_service/mohpackets/docs/schema.md -u ./chord_metadata_service/mohpackets/docs/widdershins/templates/openapi3 -c true --omitHeader true  

      - name: Convert schema.json to schema.yml
        run: python -c 'import json, yaml; json.load(open("chord_metadata_service/mohpackets/docs/schema.json")); print(yaml.dump(json.load(open("chord_metadata_service/mohpackets/docs/schema.json"))))' > chord_metadata_service/mohpackets/docs/schema.yml

      - name: Update schema with last SHA
        run: |
          REPO_NAME=${{ github.repository }}
          SHA=${{ github.sha }}

          DOCS_PATH="chord_metadata_service/mohpackets/docs/"
          SCHEMA_PATHS=(
            "${DOCS_PATH}schema.json"
            "${DOCS_PATH}schema.yml"
            "${DOCS_PATH}schema.md"
          )
          for path in "${SCHEMA_PATHS[@]}"; do
            sed -i "s|This is the RESTful API for the MoH Service.|This is the RESTful API for the MoH Service. Based on https://raw.githubusercontent.com/$REPO_NAME/$SHA/$path|" "$path"
          done

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { Octokit } = require('@octokit/rest');
            const octokit = new Octokit({ request: { fetch: fetch, }, auth: "${{ secrets.GITHUB_TOKEN }}" });
            const { commitAndPushChanges } = require("./.github/commitFile.js");

            await commitAndPushChanges('schema.json', `${{ github.head_ref }}`, fs, octokit, context);
            await commitAndPushChanges('schema.yml', `${{ github.head_ref }}`, fs, octokit, context);
            await commitAndPushChanges('schema.md', `${{ github.head_ref }}`, fs, octokit, context);