name: Docs

on:
  pull_request:
    types: [review_requested, ready_for_review]

    
jobs:
  first_job:
    name: Regenerate schema.json
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: python -m pip install -r requirements/base.txt

      - name: Generate new schema.json
        run: |
          export DJANGO_SETTINGS_MODULE=config.settings.base
          python manage.py export_openapi_schema --api chord_metadata_service.mohpackets.apis.core.api | python -m json.tool > chord_metadata_service/mohpackets/docs/schema.json
      
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: 'chord_metadata_service/mohpackets/docs/schema.json'
          commit_message: Regenerate schema.json