name: Test

on:
  push:
    branches:
      - develop
      - master
      - add-github-actions
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5433:5433

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create database
      run: |
        sudo -u postgres psql -U postgres -p 5433 -d postgres -c "alter user postgres with password 'postgres';"
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Test
      run: |
        export POSTGRES_USER="postgres" && export POSTGRES_PASSWORD="postgres" && export POSTGRES_PORT=5433
        python ./manage.py test
